apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: podinfo-httpproxy
  namespace: default
spec:
  virtualhost:
    fqdn: localhost
  routes:
    - conditions:
      - prefix: /podinfo
      services:
        - name: podinfo
          port: 9898                                 
