apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: prodinfo-ingress
  namespace: default
spec:
  ingressClassName: ambassador
  rules:
    - http:
        paths:
          - path: /podinfo
            pathType: Prefix
            backend:
              service:
                name: podinfo
                port:
                  number: 9898